### ISSUE TITLE
Swift 5 and try?

### ISSUE THREAD

**Issue by YevhenHerasymenko** [tristanhimmelman/ObjectMapper#1043]
Parsing complicated object with optional objects as a parameter does not work.

```
public struct Push: ImmutableMappable {
  public let contact: MeetingContactPush?

  public init(map: Map) throws {
    contact = try? map.value("Contact")
  }

}

public struct MeetingContactPush: ImmutableMappable {

  public let userId: Int
  public let phone: String
  public let name: String?

  public init(map: Map) throws {
    userId = try map.value("Id")
    phone = try map.value("Phone")
    name = try? map.value("Name")
  }

}

```
Contact will be always nil

**Comment by shalex9154** [comment]
try this workaround:
`contact = try? map.value("Contact") as MeetingContactPush `

**Comment by gim-** [comment]
I've been scratching my head around this which is probably related:
![Screenshot 2019-04-03 at 11 54 38](https://user-images.githubusercontent.com/1240012/55467027-147de480-5609-11e9-93ca-6db4af85efe1.png)
![Screenshot 2019-04-03 at 11 54 55](https://user-images.githubusercontent.com/1240012/55467030-147de480-5609-11e9-91ac-4a2654d21437.png)

Using @shalex9154 workaround helped. Thanks!

**Comment by sanoj00b** [comment]
Hey is project is building with Swift 5 and XCode 10.2??

**Comment by artemisia-absynthium** [comment]
Yes, it can build, but it gives this bug, a lot of warnings in console and it causes the "Migration to Swift 5 available" message to keep appearing even after said migration has been done. Please migrate and update pod 🙏🏻

**Comment by sanoj00b** [comment]
@artemisia-absynthium  which version are you targetting in Carthage?

**Comment by artemisia-absynthium** [comment]
@sanoj00b version 3.4.2

**Comment by tbechtum** [comment]
In ObjectMapper 3.4.2  there are 43 Xcode 10.2 warnings regarding modifiers public and internal for extension methods. This could be easily resolved by removing them in order to keep the warnings overview in our main projects.

Example

```
public extension Array where Element: BaseMappable {
	
	/// Initialize Array from a JSON String
	**public** init?(JSONString: String, context: MapContext? = nil) {
		if let obj: [Element] = Mapper(context: context).mapArray(JSONString: JSONString) {
			self = obj
		} else {
			return nil
		}
	}
```

Resolve: remove public modifier of above mentioned optional init method. This changes will be compatible also to Swift 4.2 projects (checked this already).

Thanks for your time and effort, cheers Thomas

**Comment by sanoj00b** [comment]
I am facing this issue, is anybody did get the resolution. Xcode 10.2 with Swift5
<img width="667" alt="Screenshot 2019-05-03 at 4 54 32 PM" src="https://user-images.githubusercontent.com/40563563/57134586-37481800-6dc4-11e9-9f0e-ec3f2ce32edc.png">

**Comment by sacred0x01** [comment]
It's still an issues - completely unable to parse optional enum values.

**Comment by sanoj00b** [comment]
> I am facing this issue, is anybody did get the resolution. Xcode 10.2 with Swift5
> <img alt="Screenshot 2019-05-03 at 4 54 32 PM" width="667" src="https://user-images.githubusercontent.com/40563563/57134586-37481800-6dc4-11e9-9f0e-ec3f2ce32edc.png">

Can anybody let me know about this? Please

**Comment by abhisheksingh9891** [comment]
I am facing the same error of but I am unable to solve it by typecasting it. 

Below is the piece of code which is causing issue:-

`let transferJSON = "{\"metadata\":{\"resultData\":[{\"execEngineRef\":\"20170821/Nedbank/489044757287\",\"transactionID\":\"28954894\",\"resultDetail\":[{\"result\":\"SOK\",\"status\":\"SUCCESS\",\"operationReference\":\"TRANSACTION\"}]}]}}"

let genericTransferResponse = try? Mapper<GenericPostResponse<TransactionResponse>>().map(JSONString: transferJSON)`

Doesn't change anything to typecast this with GenericPostResponse<TransactionResponse>.

genericTransferResponse will always be nil.

**Comment by evilutioner** [comment]
@sanoj00b if you are using Cocoapods you could remove folder `Pods/ObjectMapper` and run `pod install` for rebuilding the module with Swift 5 compiler (in compatibility mode with Swift 4.2)

**Comment by sanoj00b** [comment]
@evilutioner I am using Carthage.

**Comment by evilutioner** [comment]
@sanoj00b  For Carthage:
1. Select command line tool Xcode 10.2.x (by command `xcode-select` or Xcode IDE)
2.`carthage update ObjectMapper --no-use-binaries`

**Comment by felipe-azevedo** [comment]
I'd like @cddjr's fixed released as 5.2.2 so that I can effectively use this library with Swift 5.
@tristanhimmelman please provide this.

**Comment by felipe-azevedo** [comment]
@tristanhimmelman please use @cddjr's fix so that this lib is useable.

**Comment by tristanhimmelman** [comment]
@felipe-azevedo @cddjr If you create a PR I can merge in the fix. I unfortunately don't have the time to put this in myself.

**Comment by mickamy** [comment]
https://github.com/tristanhimmelman/ObjectMapper/pull/1057
I opened PR with @cddjr's fix.
@tristanhimmelman Would you please merge it and release new version, please?

**Comment by pmusolino** [comment]
Any news on this? :( It's really sad to see a library with a lot of users abandoned in this way.

**Comment by sacred0x01** [comment]
@pmusolino we've added `public extension Map `  into ImmutableMappable.swift, `extension ImmutableMappable` in our own codebase  and all seems to work as needed. Kinda creppy but the only possible way for now. Just use like `try? User(dictionary: dictionary)`, not `(JSON:_)` version directly
```
extension ImmutableMappable {
    init(dictionary: [String: Any], context: MapContext? = nil) throws {
        self = try Mapper(context: nil).map(JSON: dictionary)
    }
}

// optional value mappers
public extension Map {
    /// Returns a RawRepresentable type or throws an error.
    public func value<T: RawRepresentable>(_ key: String, nested: Bool? = nil, delimiter: String = ".", file: StaticString = #file, function: StaticString = #function, line: UInt = #line) throws -> T? {
        return try self.value(key, nested: nested, delimiter: delimiter, using: EnumTransform(), file: file, function: function, line: line)
    }
    
    /// Returns a `[RawRepresentable]` type or throws an error.
    public func value<T: RawRepresentable>(_ key: String, nested: Bool? = nil, delimiter: String = ".", file: StaticString = #file, function: StaticString = #function, line: UInt = #line) throws -> [T]? {
        return try self.value(key, nested: nested, delimiter: delimiter, using: EnumTransform(), file: file, function: function, line: line)
    }
    
    /// Returns a `BaseMappable` object or throws an error.
    public func value<T: BaseMappable>(_ key: String, nested: Bool? = nil, delimiter: String = ".", file: StaticString = #file, function: StaticString = #function, line: UInt = #line) throws -> T? {
        let currentValue = self.currentValue(for: key, nested: nested, delimiter: delimiter)
        guard let JSONObject = currentValue else {
            throw MapError(key: key, currentValue: currentValue, reason: "Found unexpected nil value", file: file, function: function, line: line)
        }
        return try Mapper<T>(context: context).mapOrFail(JSONObject: JSONObject)
    }

    /// Returns a `[BaseMappable]` or throws an error.
    public func value<T: BaseMappable>(_ key: String, nested: Bool? = nil, delimiter: String = ".", file: StaticString = #file, function: StaticString = #function, line: UInt = #line) throws -> [T]? {
        let currentValue = self.currentValue(for: key, nested: nested, delimiter: delimiter)
        guard let jsonArray = currentValue as? [Any] else {
            throw MapError(key: key, currentValue: currentValue, reason: "Cannot cast to '[Any]'", file: file, function: function, line: line)
        }
        
        return try jsonArray.map { JSONObject -> T in
            return try Mapper<T>(context: context).mapOrFail(JSONObject: JSONObject)
        }
    }
    
    /// Returns a `[BaseMappable]` using transform or throws an error.
    public func value<Transform: TransformType>(_ key: String, nested: Bool? = nil, delimiter: String = ".", using transform: Transform, file: StaticString = #file, function: StaticString = #function, line: UInt = #line) throws -> [Transform.Object]? {
        let currentValue = self.currentValue(for: key, nested: nested, delimiter: delimiter)
        guard let jsonArray = currentValue as? [Any] else {
            throw MapError(key: key, currentValue: currentValue, reason: "Cannot cast to '[Any]'", file: file, function: function, line: line)
        }
        
        return try jsonArray.map { json -> Transform.Object in
            guard let object = transform.transformFromJSON(json) else {
                throw MapError(key: "\(key)", currentValue: json, reason: "Cannot transform to '\(Transform.Object.self)' using \(transform)", file: file, function: function, line: line)
            }
            return object
        }
    }
 
    /// Returns a `[String: BaseMappable]` or throws an error.
    public func value<T: BaseMappable>(_ key: String, nested: Bool? = nil, delimiter: String = ".", file: StaticString = #file, function: StaticString = #function, line: UInt = #line) throws -> [String: T]? {
        
        let currentValue = self.currentValue(for: key, nested: nested, delimiter: delimiter)
        guard let jsonDictionary = currentValue as? [String: Any] else {
            throw MapError(key: key, currentValue: currentValue, reason: "Cannot cast to '[String: Any]'", file: file, function: function, line: line)
        }
        var value: [String: T] = [:]
        for (key, json) in jsonDictionary {
            value[key] = try Mapper<T>(context: context).mapOrFail(JSONObject: json)
        }
        return value
    }
    
    /// Returns a `[String: BaseMappable]` using transform or throws an error.
    public func value<Transform: TransformType>(_ key: String, nested: Bool? = nil, delimiter: String = ".", using transform: Transform, file: StaticString = #file, function: StaticString = #function, line: UInt = #line) throws -> [String: Transform.Object]? {
        
        let currentValue = self.currentValue(for: key, nested: nested, delimiter: delimiter)
        guard let jsonDictionary = currentValue as? [String: Any] else {
            throw MapError(key: key, currentValue: currentValue, reason: "Cannot cast to '[String: Any]'", file: file, function: function, line: line)
        }
        var value: [String: Transform.Object] = [:]
        for (key, json) in jsonDictionary {
            guard let object = transform.transformFromJSON(json) else {
                throw MapError(key: key, currentValue: json, reason: "Cannot transform to '\(Transform.Object.self)' using \(transform)", file: file, function: function, line: line)
            }
            value[key] = object
        }
        return value
    }
    
    // MARK: [[BaseMappable]]
    /// Returns a `[[BaseMappable]]` or throws an error.
    public func value<T: BaseMappable>(_ key: String, nested: Bool? = nil, delimiter: String = ".", file: StaticString = #file, function: StaticString = #function, line: UInt = #line) throws -> [[T]]? {
        
        let currentValue = self.currentValue(for: key, nested: nested, delimiter: delimiter)
        guard let json2DArray = currentValue as? [[Any]] else {
            throw MapError(key: key, currentValue: currentValue, reason: "Cannot cast to '[[Any]]'", file: file, function: function, line: line)
        }
        return try json2DArray.map { jsonArray in
            try jsonArray.map { jsonObject -> T in
                return try Mapper<T>(context: context).mapOrFail(JSONObject: jsonObject)
            }
        }
    }
    
    /// Returns a `[[BaseMappable]]` using transform or throws an error.
    public func value<Transform: TransformType>(_ key: String, nested: Bool? = nil, delimiter: String = ".", using transform: Transform, file: StaticString = #file, function: StaticString = #function, line: UInt = #line) throws -> [[Transform.Object]]? {
        
        let currentValue = self.currentValue(for: key, nested: nested, delimiter: delimiter)
        guard let json2DArray = currentValue as? [[Any]] else {
            throw MapError(key: key, currentValue: currentValue, reason: "Cannot cast to '[[Any]]'",
                           file: file, function: function, line: line)
        }
        
        return try json2DArray.map { jsonArray in
            try jsonArray.map { json -> Transform.Object in
                guard let object = transform.transformFromJSON(json) else {
                    throw MapError(key: "\(key)", currentValue: json, reason: "Cannot transform to '\(Transform.Object.self)' using \(transform)", file: file, function: function, line: line)
                }
                return object
            }
        }
    }
}

```

**Comment by tristanhimmelman** [comment]
I've just merged the fix for this. Sorry for the delay!

The library has not been abandoned, I just do not have as much time as I used to to maintain it. If there are volunteers to help support I would be happy for the help.

**Comment by felipe-azevedo** [comment]
Thank you so much, folks!

**Comment by felipe-azevedo** [comment]
@tristanhimmelman, is there a way to reopen this?
The fix worked for most of the things, but it is still failing for mapping optional enums. They are always map to nil even though there is a value in the JSON.

**Comment by felipe-azevedo** [comment]
I think the issue I mentioned is going to be fixed on #1059.

**Comment by tbechtum** [comment]
Thanks for your work and effort: to me and my use cases ObjectMapper 3.5.0 and Swift 5 is working fine.
